# Generated by Django 5.1.7 on 2025-03-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='文件内容')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('formulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input_file', to='electrolyte.electrolyteformulation', verbose_name='配方')),
            ],
            options={
                'verbose_name': '输入文件',
                'verbose_name_plural': '输入文件',
            },
        ),
    ]
