# Generated by Django 3.2.25 on 2025-03-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyte', '0002_inputfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='output_dir',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='输出目录路径'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='slurm_job_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SLURM作业ID'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('submitted', '已提交'), ('queued', '排队中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
