# Generated by Django 3.2.25 on 2025-03-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrolyte', '0003_auto_20250320_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvent',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='密度'),
        ),
        migrations.AddField(
            model_name='solvent',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='完整名称'),
        ),
        migrations.AddField(
            model_name='solvent',
            name='molecular_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='分子量'),
        ),
    ]
